Finecap-repositorio/core/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "core"

urlpatterns = [
    
    path("", views.HomeView.as_view(), name="index" )
    ]

Finecap-repositorio/main/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("reservas.urls", namespace="reservas")),
    path("", include("stands.urls", namespace="stands")),
    path('accounts/', include('allauth.urls')),
    path('', include("core.urls", namespace="core"))
]

Finecap-repositorio/reservas/urls.py
from django.contrib import admin
from django.urls import path
from reservas.views import ReservaCreateView, ReservaDeleteView, ReservaDetailView, ReservasListView, ReservaUpdateView

app_name = "resevas"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cadastro_reserva/", ReservaCreateView.as_view(), name="cadastro_reserva"),
    path('visualizar_reservas/', ReservasListView.as_view(), name='visualizar_reservas'),
    path('remover_reserva/<int:pk>/', ReservaDeleteView.as_view(), name="remover_reserva"),
    path('detalhe_reserva/<int:pk>/', ReservaDetailView.as_view(), name='detalhe_reserva'),
    path('update/<int:pk>/', ReservaUpdateView.as_view(), name="editar"),
    ]

Finecap-repositorio/stands/urls.py
from django.contrib import admin
from django.urls import path
from stands.views import StandCreateView, StandDeleteView, StandListView, StandUpdateView  

app_name = "stands"

urlpatterns = [
    path('stands_visualizar/', StandListView.as_view(), name='stands_visualizar'),
    path('stands_cadastro/', StandCreateView.as_view(), name="stands_cadastro"),
    path('remover_stand/<int:pk>/', StandDeleteView.as_view(), name="remover_stand"),
    path('update_stand/<int:pk>/', StandUpdateView.as_view(), name="editar_stand"),

]

Finecap-repositorio/core/models.py
from django.db import models

# Create your models here.

Finecap-repositorio/reservas/models.py
from django.db import models
from stands.models import Stand



class Reserva(models.Model):
   
    nome_empresa = models.CharField(max_length=150)
    categoria_empresa = models.CharField(max_length=150)
    cnpj = models.CharField(max_length=11)
    quitado = models.BooleanField(default=False)
    stand = models.ForeignKey(Stand, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome_empresa

Finecap-repositorio/stands/models.py
from django.db import models


class Stand(models.Model):
    localizacao = models.CharField(max_length=150)
    valor = models.DecimalField(verbose_name="Valor",decimal_places=2,max_digits=6)

    def __str__(self):
        return self.localizacao

Finecap-repositorio/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

Finecap-repositorio/reservas/forms.py
from django.forms import ModelForm
from django import forms
from .models import Reserva

class ReservaForm(ModelForm):

    class Meta:
        model = Reserva
        fields = '__all__'
        widgets = {
            'cnpj' : forms.TextInput(attrs={'class': 'form-control' }),
            'nome_empresa' : forms.TextInput(attrs={'class': 'form-control' }),
            'categoria_empresa' : forms.TextInput(attrs={'class': 'form-control' }),
            'stand': forms.Select(attrs={'class': 'form-control' }),
        }

Finecap-repositorio/stands/forms.py
from django.forms import ModelForm
from django import forms
from decimal import Decimal
from .models import Stand

class StandForm(ModelForm):
    class Meta:
        model = Stand
        fields = '__all__'

    localizacao = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    valor = forms.DecimalField(widget=forms.TextInput(attrs={'class': 'money form-control', 'placeholder': 'Valor do stand'}), localize=True)

    def clean_valor(self):
        valor = self.cleaned_data["valor"]
        if isinstance(valor, str):
            try:
                valor = Decimal(valor.replace(",", ""))
            except ValueError:
                raise forms.ValidationError("Informe um número válido para o valor.")
        return valor

Finecap-repositorio/core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.messages import views
from django.contrib.auth.mixins import LoginRequiredMixin
from reservas.models import Reserva
from stands.models import Stand

class HomeView(LoginRequiredMixin, generic.TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_reservas'] = Reserva.objects.count()
        return context

Finecap-repositorio/reservas/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Reserva
from .forms import ReservaForm
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.messages import views
from django.contrib.auth.mixins import LoginRequiredMixin
from users.permissions import GerentePermission


#lista#

class ReservasListView(LoginRequiredMixin, generic.ListView):
    model = Reserva
    template_name = "visualizar_reservas.html"
    paginate_by = 4

#CRUD#

class ReservaCreateView(LoginRequiredMixin, generic.CreateView):
    model = Reserva
    form_class = ReservaForm
    success_url = reverse_lazy("reservas:visualizar_reservas")
    template_name = "cadastro_reserva.html"

    def form_valid(self, form):
        messages.success(self.request, "Reserva cadastrada!")
        return super().form_valid(form)

class ReservaUpdateView(GerentePermission,LoginRequiredMixin, generic.UpdateView):
    model = Reserva
    form_class = ReservaForm
    success_url = reverse_lazy("reservas:visualizar_reservas")
    template_name = "cadastro_reserva.html"
   
    def form_valid(self, form):
        messages.success(self.request, "Reserva Atualizado!")
        return super().form_valid(form)

class ReservaDeleteView(GerentePermission,LoginRequiredMixin, views.SuccessMessageMixin,generic.DeleteView):
    model = Reserva
    success_url = reverse_lazy("reservas:visualizar_reservas")
    success_message = "reserva deletada!"
  
#Detalhe#

class ReservaDetailView(LoginRequiredMixin, generic.DetailView):
    model = Reserva
    template_name = "detalhe_reserva.html"  

Finecap-repositorio/stands/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Stand
from .forms import StandForm
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.messages import views
from django.contrib.auth.mixins import LoginRequiredMixin
from users.permissions import GerentePermission

#Lista#

class StandListView(LoginRequiredMixin, generic.ListView):
    model = Stand
    template_name = "stands_visualizar.html"
    paginate_by = 4

#CRUD#

class StandCreateView(GerentePermission,LoginRequiredMixin, generic.CreateView):
    model = Stand
    form_class = StandForm
    success_url = reverse_lazy("stands:stands_visualizar")
    template_name = "stands_cadastro.html"

    def form_valid(self, form):
        messages.success(self.request, "Stand cadastrada!!")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        print(form.errors)
        return self.render_to_response(self.get_context_data(form=form))

class StandUpdateView(GerentePermission,LoginRequiredMixin, generic.UpdateView):
    model = Stand
    form_class = StandForm
    success_url = reverse_lazy("stands:stands_visualizar")
    template_name = "stands_cadastro.html"

    def form_valid(self, form):
        messages.success(self.request, "Stand Atualizado!")
        return super().form_valid(form)

class StandDeleteView(GerentePermission,LoginRequiredMixin, views.SuccessMessageMixin,generic.DeleteView):
    model = Stand
    success_url = reverse_lazy("stands:stands_visualizar")
    success_message = "Stand removido!"

Finecap-repositorio/users/views.py
from django.shortcuts import render

# Create your views here.

Finecap-repositorio/core/templates/index.html
{% extends 'base.html' %}



    {% block center %}
    <section class="py-5">
        <div class="container px-5">
            <div class="bg-light rounded-4 py-5 px-4 px-md-5">
                <div class="text-center mb-5">                
                    <h1 class="fw-bolder">FINECAP 2023</h1>
                    <p class="lead fw-normal text-muted mb-0">Faça sua reserva</p>
                </div>
    
                <div class="text-center mb-5"> 

                  {% if messages %}
                  <div class="messages">
                 {% for message in messages %}
                  <div class="alert alert-{{ message.tags }}">
                 {{ message }}
                 </div>
                {% endfor %}
                </div>
                {% endif %}
    
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6">
                      <a href="{% url 'reservas:cadastro_reserva' %}" class="btn btn-success mb-3">Cadastre aqui</a>     
                      
                          <div class="card text-white bg-primary mb-3">
                            <div class="card-header"></div>
                            <div class="card-body">
                              <h5 class="card-title">Total de Reservas já cadastradas</h5>
                              <p class="card-text">{{ total_reservas }}</p>
                            </div>
                          </div>
                        
                      
                    </div>
                </div>
    
             
              </div>
            </div>
        </div>
      </section>
      {% endblock %}

Finecap-repositorio/reservas/templates/cadastro_reserva.html
  {% extends 'base.html' %}



    {% block center %}
    <section class="py-5">
        <div class="container px-5">
            
            <div class="bg-light rounded-4 py-5 px-4 px-md-5">
                <div class="text-center mb-5">
                    
                    <h1 class="fw-bolder">FINECAP 2023</h1>
                    <p class="lead fw-normal text-muted mb-0">Faça sua reserva</p>
                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6">
                      
                        <form method="post" id="contactForm" data-sb-form-api-token="API_TOKEN">
                            {% csrf_token %}
                           
                            <div class="form-floating mb-3">
            
                                <p for="name">Nome da empresa</p>
                                {{ form.nome_empresa }}
                                <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                            </div>
                            
                            <div class="form-floating mb-3">
                                
                                <p for="email">Categoria da empresa</p>
                                {{ form.categoria_empresa }}
                                <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                                <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                            </div>
                           
                            <div class="form-floating mb-3">
                                
                                <p for="phone">CNPJ</p>
                                
                                {{ form.cnpj }}
                                <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                            </div>
    
    
    
    
                            <div class="form-floating mb-3">
                                
                                <p for="phone">Stand</p>
                                
                                {{ form.stand }}
                                <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                            </div>
    
    
    
    
    
    
                            <div class="d-none" id="submitSuccessMessage">
                                <div class="text-center mb-3">
                                    <div class="fw-bolder">Form submission successful!</div>
                                    To activate this form, sign up at
                                    <br />
                                    <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                </div>
                            </div>
                           
                            <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                            
                            <div class="d-grid"><button type="submit" class="btn btn-primary">Enviar</button></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
      </section>
      {% endblock %}
    

Finecap-repositorio/reservas/templates/detalhe_reserva.html
{% extends 'base.html' %}
{% block center %}

<section class="py-5">
    <div class="container px-5">
        <div class="bg-light rounded-4 py-5 px-4 px-md-5">
            <div class="text-center mb-5">                
                <h1 class="fw-bolder">FINECAP 2023</h1>
                <p class="lead fw-normal text-muted mb-0">Ficha de detalhes</p>
            </div>
  <div class="text-center mb-5"> 




  
    <br>
    <br>   
        <hr>
        <div class="mb-3">
            <h5>Nome da empresa:</h5>
            <p>{{ object.nome_empresa }}</p>
        </div>
        
        <div class="mb-3">
            <hr>
            <h5>Categoria da empresa</h5>
            <p>{{ object.categoria_empresa }}</p>
        </div>

        <div class="mb-3">
            <hr>
            <h5>CNPJ</h5>
            <p>{{ object.cnpj }}</p>
        </div>

        <div class="mb-3">
            <hr>
            <h5>Stand</h5>
            <p>{{ object.stand }}</p>
        </div>

        <div class="mb-3">
            <hr>
            <h5>Situação</h5>
            {% if object.quitado %}
            <p>Quitado</p>
            {% else %}
            <p>Aguardando</p>
            {% endif %}
        </div>
        <hr>


        <a class="btn btn-dark btn-lg" href="{% url 'reservas:visualizar_reservas' %}">VOLTAR</a>
    
    </div>
</div>
</div>

</section>
{% endblock %}

Finecap-repositorio/reservas/templates/reservas/reserva_confirm_delete.html
{% extends 'base.html' %}
{% block center %}

<section class="py-5">
  <div class="container px-5">
      <div class="bg-light rounded-4 py-5 px-4 px-md-5">
          <div class="text-center mb-5">                
              <h1 class="fw-bolder">FINECAP 2023</h1>
              <p class="lead fw-normal text-muted mb-0">Lista de reservas</p>
          </div>
<div class="text-center mb-5"> 


<h3>Por favor, confirme a ação.</h3>
<form method="post">
  {% csrf_token %}
    <p>Realmente tem absoluta certeza de que deseja excluir a reserva "{{ object }}"?</p>
    {{ form }}
  <button type="submit" class="btn btn-danger">Confirmar</button>
</form>


</div>
</div>
</div>

</section>
{% endblock %}

Finecap-repositorio/reservas/templates/visualizar_reservas.html
{% extends 'base.html' %}

{% block center %}
<section class="py-5">
  <div class="container px-5">
      <div class="bg-light rounded-4 py-5 px-4 px-md-5">
          <div class="text-center mb-5">                
              <h1 class="fw-bolder">FINECAP 2023</h1>
              <p class="lead fw-normal text-muted mb-0">Lista de reservas</p>
          </div>
 


  <div class="text-center mb-5">   

    
  {% if messages %}
  <div class="messages">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message }}
    </div>
    {% endfor %}
  </div>
  {% endif %}

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Nome</th>  
        <th>CNPj</th>
        <th>Stand</th>
      </tr>
    </thead>
    <tbody>

      {% for object in object_list %}
    <tr>
      <td>{{ object.nome_empresa }}</td>
      <td>{{ object.stand }}</td>
      <td>{{ object.cnpj }}</td>
        <td>
            <a href="{% url 'reservas:editar' object.id %}" class="btn btn-outline-primary">Editar</a>
            <a href="{% url 'reservas:detalhe_reserva' object.id %}" class="btn btn-outline-success">Detalhe</a>
            <a href="{% url 'reservas:remover_reserva' object.id %}" class="btn btn-outline-danger">Deletar</a>
        </td>
      </tr>
      {% endfor %}
    
    </tbody>
  </table>




  {% if page_obj.has_other_pages %}
  <nav>
      <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
              <li class="page-item">
                  <a class="page-link" href="?page=1">
                      Começo
                  </a>
              </li>
              
          {% endif %}

          {% for page_number in page_obj.paginator.page_range %}

              {% if page_number <= page_obj.number|add:3 and page_number >= page_obj.number|add:-3 %}
                  {% if page_obj.number == page_number %}
                      <li class="page-item active">
                          <a class="page-link" href="?page={{ page_number }}">
                              {{ page_number }}
                          </a>
                      </li>
                  {% else %}
                      <li class="page-item">
                          <a class="page-link" href="?page={{ page_number }}">
                              {{ page_number }}
                          </a>
                      </li>
                  {% endif %}
              {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
              
              <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                      Final
                  </a>
              </li>
          {% endif %}
      </ul>
  </nav>
{% endif %}
  
</div>
 

</div>
</div>
</section>
{% endblock %}

Finecap-repositorio/stands/templates/stands/stand_confirm_delete.html
{% extends 'base.html' %}
{% block center %}

<section class="py-5">
  <div class="container px-5">
      <div class="bg-light rounded-4 py-5 px-4 px-md-5">
          <div class="text-center mb-5">                
              <h1 class="fw-bolder">FINECAP 2023</h1>
              <p class="lead fw-normal text-muted mb-0">Lista de reservas</p>
          </div>
<div class="text-center mb-5"> 


<h3>Por favor, confirme a ação.</h3>
<form method="post">
  {% csrf_token %}
    <p>Realmente tem absoluta certeza de que deseja excluir a reserva "{{ object }}"?</p>
    {{ form }}
  <button type="submit" class="btn btn-danger">Confirmar</button>
</form>


</div>
</div>
</div>

</section>
{% endblock %}

Finecap-repositorio/stands/templates/stands_cadastro.html
{%  extends 'base.html' %}

{% block center %}
<section class="py-5">
    <div class="container px-5">
        
        <div class="bg-light rounded-4 py-5 px-4 px-md-5">
            <div class="text-center mb-5">
                
                <h1 class="fw-bolder">FINECAP 2023</h1>
                <p class="lead fw-normal text-muted mb-0">Faça sua reserva</p>
            </div>
            <div class="row gx-5 justify-content-center">
                <div class="col-lg-8 col-xl-6">
                  



        <form method="post" id="contactForm" data-sb-form-api-token="API_TOKEN">
 
        {% csrf_token %}


        <div class="form-floating mb-3">
                            
            <p for="phone">Localização</p>
            
            {{ form.localizacao }}
            <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
        </div>


        <div class="form-floating mb-3">
            
            <p for="phone">Valor</p>
            
            {{ form.valor }}
            <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
        </div>



        <div class="d-none" id="submitSuccessMessage">
            <div class="text-center mb-3">
                <div class="fw-bolder">Form submission successful!</div>
                To activate this form, sign up at
                <br />
                <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
            </div>
        </div>
       
        <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
        
        <div class="d-grid"><button type="submit" class="btn btn-primary">Enviar</button></div>
    </form>
</div>
</div>
</div>
</div>
</section>
{% endblock %}

Finecap-repositorio/stands/templates/stands_visualizar.html
{% extends 'base.html' %}

{% block center %}
<section class="py-5">
  <div class="container px-5">
      <div class="bg-light rounded-4 py-5 px-4 px-md-5">
          <div class="text-center mb-5">                
              <h1 class="fw-bolder">FINECAP 2023</h1>
              <p class="lead fw-normal text-muted mb-0">Lista de reservas</p>
          </div>
  <div class="text-center mb-5">   
  {% if messages %}
  <div class="messages">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message }}
    </div>
    {% endfor %}
  </div>
  {% endif %}

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Localização</th>
        <th>Preço</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>

        {% for object in object_list %}
        <tr>
          <td>{{ object.localizacao }}</td>
          <td>R$ {{ object.valor }}</td>
          <td>
          <a href="{% url 'stands:editar_stand' object.id %}" class="btn btn-outline-primary">Editar</a>
          <a href="{% url 'stands:remover_stand' object.id %}" class="btn btn-outline-danger">Deletar</a>   
          </td>
    
        </tr>
        {% endfor %}
    
    </tbody>
  </table>
  
 



  {% if page_obj.has_other_pages %}
  <nav>
      <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
              <li class="page-item">
                  <a class="page-link" href="?page=1">
                      Começo
                  </a>
              </li>
              
          {% endif %}

          {% for page_number in page_obj.paginator.page_range %}

              {% if page_number <= page_obj.number|add:3 and page_number >= page_obj.number|add:-3 %}
                  {% if page_obj.number == page_number %}
                      <li class="page-item active">
                          <a class="page-link" href="?page={{ page_number }}">
                              {{ page_number }}
                          </a>
                      </li>
                  {% else %}
                      <li class="page-item">
                          <a class="page-link" href="?page={{ page_number }}">
                              {{ page_number }}
                          </a>
                      </li>
                  {% endif %}
              {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
              
              <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                      Final
                  </a>
              </li>
          {% endif %}
      </ul>
  </nav>
{% endif %}
{% endblock %}

Finecap-repositorio/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content />
        <meta name="author" content />

        


        <title>FINECAP2023</title> 
       
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet" />
        
        <link href="{% static 'css/int.css' %}" rel="stylesheet">
        
    </head>
    <body class="d-flex flex-column">
        <main class="flex-shrink-0">
            

            <nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
                <div class="container px-5">
                    <a class="navbar-brand" href="http://127.0.0.1:8000/"><span class="fw-bolder text-primary">FELIPECAP 2023</span></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    
                    {% if user.is_authenticated %}
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">

                            
                            <li class="nav-item"><a class="nav-link" href="{% url 'reservas:visualizar_reservas' %}">Reservas</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'stands:stands_visualizar' %}">Stands</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'stands:stands_cadastro' %}">Cadastro de Stand</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'reservas:cadastro_reserva' %}">Cadastro de Reserva</a></li>
                            
                        </ul>
                    </div>
                    {% endif %}
                </div>
            </nav>
            

            {% block center %}
            {% endblock %}      
        </main> 

        <footer class="bg-white py-4 mt-auto">
            <div class="container px-5">
                <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                    <div class="col-auto"><div class="small m-0">Copyright &copy; Felipe Osório Bezerra</div></div>
                    <div class="col-auto">
                      

                        {% if user.is_authenticated %}
                        <form method="post" action="{% url 'account_logout' %}">
                          {% csrf_token %}
                          {% if redirect_field_value %}
                          <input type="hidden" name="{{ redirect_field_name }}"
                                 value="{{ redirect_field_value }}" />
                          {% endif %}
                          <button class="btn btn-outline-danger" type="submit">
                            Logout</button>
                          </form>
                          
                          {% endif %}

                    </div>
                </div>
            </div>
        </footer>

        {% block javascript %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
        integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"
        integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.js"
        integrity="sha512-0XDfGxFliYJPFrideYOoxdgNIvrwGTLnmK20xZbCAvPfLGQMzHUsaqZK8ZoH+luXGRxTrS46+Aq400nCnAT0/w=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
      
            <script>
              $(document).ready(function () {
                $('.money').mask('0000,00', { reverse: true })
              })
            </script>
            {% endblock javascript %}
    </body>
</html>
 
 
 
 











  




 



























































































































































































 

Finecap-repositorio/templates/layouts/alerts.html
{% if form.errors %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <div class="d-flex align-items-center">
    <i class="fas fa-exclamation-triangle fa-lg" aria-hidden="true"></i>
    <div class="ml-3">
      <strong>Atenção.</strong>
      <ul class="mb-0">
        {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
        {% endfor %}
        {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}
              <li><strong>{{ field.label }}:</strong> {{ error|escape }}</li>
            {% endfor %}
          {% endfor %}
        {% endif %}
      </ul>
    </div>
  </div>
  <button type="button" class="close" data-dismiss="alert" aria-label="Fechar">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}

Finecap-repositorio/templates/layouts/messages.html
{% for message in messages %}
    <div class="alert alert-success d-flex align-items-center justify-content-between mb-3" role="alert" data-message-id="{{ forloop.counter }}">
        <div class="d-flex align-items-center">
            <div class="icon mr-2 align-middle"><i class="fas fa-check-circle fa-lg" aria-hidden="true"></i></div>
            <div class="content" style="margin-top: 15px; margin-left: 10px;">
                <span class="message-body">
                    <p>{{ message|safe }}</p>
                </span>
            </div>
        </div>
        <div class="close">
            <button class="btn btn-outline-danger circle small" type="button" aria-label="Fechar">
                <i class="fas fa-times" aria-hidden="true"></i>
            </button>
        </div>
    </div>
{% endfor %}

<script>
    function fecharMensagem(messageId) {
        const mensagem = document.querySelector(`[data-message-id="${messageId}"]`);
        if (mensagem) {
            mensagem.remove();
        }
    }
</script>